#!/usr/bin/env python3
"""Generate the Go dependency notices and carry the Rust core's complete notice."""
import json
import os
from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parent.parent
rust = Path(os.environ.get("SDK_RUST_DIR", root.parent / "sdk-rust"))
parts = ["IceRoot SDK for Go\n\nLicensed under the Apache License, Version 2.0 (see LICENSE).\n\n"
         "Generated by scripts/notice.py. The embedded core carries the Rust workspace's\n"
         "complete dependency notice below, including optional native dependencies.\n"]
for name in ["github.com/tetratelabs/wazero", "golang.org/x/sys"]:
    module = json.loads(subprocess.check_output(["go", "list", "-m", "-json", name], cwd=root))
    parts.append(f"\n{name} {module['Version']}\nhttps://{name}\n\n")
    parts.append((Path(module["Dir"]) / "LICENSE").read_text())
    # A module's own NOTICE (Apache-2.0, section 4(d)) and patent grant travel with its licence.
    for extra in ["NOTICE", "PATENTS"]:
        path = Path(module["Dir"]) / extra
        if path.exists():
            parts.append(f"\n{name} {extra}\n\n")
            parts.append(path.read_text())
parts.append("\nEmbedded Rust core dependency notice\n\n")
parts.append((rust / "NOTICE").read_text())
text = "".join(parts)
path = root / "NOTICE"
if "--check" in sys.argv:
    if not path.exists() or path.read_text() != text:
        sys.exit("NOTICE differs; run python3 scripts/notice.py")
    print("NOTICE is current")
else:
    path.write_text(text)
    print("NOTICE written")
